### PR TITLE
Fix all keyboard handling issues

### LINKED ISSUE #24: Cannot repeat non-symbol keys by holding down
Useful e.g. in the shop to buy many bullets if your fire key is bound to e.g. ctrl or alt.

I think we need to convert the keyboard handling to use `SDL_GetKeyboardState` to achieve this, because SDL doesn't generate key repeat events for these keys.

### LINKED ISSUE #69: Name changing input accepts non-visible characters
If pressing buttons like Ctrl, Alt, Shift etc. during player name change (Options - Player Options - Change Pl[1,2] Keys), invisible characters are added. Characters should be filtered to only contain visible characters (+ maybe space).

### LINKED ISSUE #72: Some keys are incorrectly mapped when changing keys
Tested on Windows 10.

When changing player keys (Options - Player Options - Define Keys [1,2]), some keys like **Z**, **Left Shift**, **Alt Gr** or **F1-F12** either show incorrectly or doesn't bind.

### LINKED ISSUE #81: Pressing space should toggle the map
Map is bound to `M` currently.

According to original README and testing on DosBox, space toggles the map in v1.21.

### LINKED ISSUE #84: Keybindings in OPTIONS.CFG are not the same as in original
Keys: forward, backward, turn counter clockwise, turn clockwise, shoot, change weapon, strafe, strafe left, strafe right.
Player 1: up, down, left, right, ctrl, shift, alt gr, comma, period
Player 2: w, s, a, d, tab, caps lock, `, 1, 2

### PR DESCRIPTION
**Pull request by akheron**
Fix non-symbol key repeat on all platforms. Fixes #24.

Change all key handling to SDL scancodes. This fixes problems with overlapping keys, and allows the user to use any key in key bindings. Fixes #72.

Only allow certain characters for player name and server address. Fixes #69.

Set default keybindings to OPTIONS.CFG as they are in v1.21. Fixes #84.

Toggle map with space instead of M. Fixes #81.

### CODE REVIEW

File: SRC/KEYB.H [hunk 1]
```diff
@@ -1,52 +1,24 @@
...
+    void init( int );
+    void deinit();
+    void clear_stack();
+    int kbhit();
+    int getch();
+    void handle_event( const SDL_Event * );
+}
+}
+
+namespace k = tk_port::keyb;
```
Comment (veikkos) [inline SRC/KEYB.H]: In general it's not encouraged to declare namespace aliases in header files (as opposed to src files) because it is now visible to all files including this header. It increases the risk of name clash and is slightly confusing when one needs to track down where the `k` is defined as it behaves like a "global" thing.

But I don't consider it as a huge issue in this context, it allows more original feel in code.

File: SRC/KEYB.CPP [hunk 2]
```diff
@@ -0,0 +1,153 @@
+#include <SDL.h>
+#include <cstdint>
+#include "KEYB.H"
+
+namespace tk_port
+{
+namespace keyb
+{
+
+char state[256];
```
Comment (veikkos) [inline SRC/KEYB.CPP]: Notpicking but `256` could be in const variable to avoid re-writing it.

File: SRC/KEYB.CPP [hunk 3]
```diff
@@ -118,34 +149,70 @@ int getch()
...
+            _kbhit_flag = true;
+            break;
+        }
 
-    if ( down )
-    {
-        const uint8_t tk_key = remap_key( e->key.keysym.sym );
+        case SDL_KEYUP:
+        {
+            uint8_t scancode_index = get_scancode_index( e->key.keysym.sym, e->key.keysym.scancode );
```
Comment (veikkos) [inline SRC/KEYB.CPP]: Could `const` some variables, but that's not critical. :)

File: SRC/KEYB.CPP [hunk 4]
```diff
@@ -18,11 +18,11 @@ int _last_getch;
 
 struct key_repeat
 {
+    int key;
     uint32_t pressed_time;
     int repeats;
 };
-
-std::map<uint8_t, key_repeat> pressed_keys;
+key_repeat pressed_key = { -1, 0, 0 };
```
Comment (veikkos) [inline SRC/KEYB.CPP]: I'd const that -1 to `INVALID_KEY` or similar.

File: SRC/KEYB.H (hunk 1 above)
Comment (akheron) [reply SRC/KEYB.H]: Yeah, this keeps the original feel, and `k` was a global variable in `GLOBVARS.H` already anyway :)

**Comment by akheron** [comment]
@akx noticed that shop cannot be exited anymore and fixed it! :)

**Comment by akheron** [comment]
There's one problem on macOS: The default keybinding for player 1 shoot is right ctrl, which doesn't exist in all Apple keyboards, including the built-in keyboard for all Macbooks. I'm not sure if we should try to fix this somehow, or just document in the readme that you have to change keybindings before playing if your keyboard doesn't have a right ctrl.

File: SRC/GAME.CPP [hunk 5]
```diff
@@ -593,26 +593,26 @@ void chkeys()
...
 
-    if ( k.state[static_cast<int>('M')] )
+    if ( k::state(k::SPACE) )
     {
         MAP_ON = !MAP_ON ? 1 : 0;
-        k.state[static_cast<int>('M')] = 0;
+        k::clear(k::SPACE);
     }
-    if ( k.state[static_cast<int>('F')] )
+    if ( k::state(k::CHR_F) )
```
Comment (veikkos) [inline SRC/GAME.CPP]: TK321 on DOSBox has FPS on F5.

File: SRC/KEYB.CPP [hunk 6]
```diff
@@ -0,0 +1,144 @@
...
+#include <SDL.h>
+#include "KEYB.H"
+
+namespace tk_port
+{
+namespace keyb
+{
+
+const uint32_t KEY_REPEAT_TIMER_CODE = 43615681;  // Random number heh heh
+const uint32_t SYMBOL_KEY_REPEAT_START = 500;     // ms
```
Comment (veikkos) [inline SRC/KEYB.CPP]: Repeat start delay is considerably shorter on DOSBox. Maybe half or so.

Comment (akheron) [reply SRC/KEYB.CPP]: I tried to search around for how the key repeat is actually implemented (i.e. does it happen in the window system, in the keyboard driver, somewhere else in the OS, or in the keyboard itself) but didn't find much info. My point is whether it can depend on user configuration or not.

Do you think we should make the initial interval faster?

Comment (veikkos) [reply SRC/KEYB.CPP]: Feel free to go ahead with this. It can be tweaked later if needed.
