### PR TITLE
Transmit steams and spot lights to clients

### LINKED ISSUE #167: Smokes and lights not working in network games
Smokes and lights not working in network games.

### PR DESCRIPTION
**Pull request by veikkos**
Fixes #167 

Transmit steams and spot lights to clients. Implemented with original code look and feel, incl. copy-paste, random indentation and all. 😅

### CODE REVIEW

File: SRC/NET/NETDEFS.CPP [hunk 1]
```diff
@@ -29,5 +29,7 @@ int IPXMSGLEN[] =
     0, // messsssssaaaaaaaaaaage
     0, // saund
     0, // NEWPLAYERDATA
-    0  // PLAYERDISCONNECTED
+    0, // PLAYERDISCONNECTED
+    0, // SENDLEVELSTEAMS
```
Comment (akheron) [inline SRC/NET/NETDEFS.CPP:33]: Wrong comment?

Comment (veikkos) [reply SRC/NET/NETDEFS.CPP:33]: Woops! Yep, old comment. Updating.
