### PR TITLE
Better level bounds checking (and developer QOL tools)

### LINKED ISSUE #122: Segfault in Enemy::move()
Via @akheron 
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055cd35509ca0 in Enemy::move(int, int) ()
[Current thread is 1 (Thread 0x7fbbf1d93740 (LWP 11856))]
(gdb) bt
#0  0x000055cd35509ca0 in Enemy::move(int, int) ()
#1  0x000055cd3551d262 in move_enemies() ()
#2  0x000055cd35520399 in game_shit() ()
#3  0x000055cd35525515 in game() ()
#4  0x000055cd35526080 in menu() ()
#5  0x000055cd35502ef8 in main ()
```

### PR DESCRIPTION
**Pull request by akx**
* Replaces error-prone direct `level[y * w + x]` accesses with a helper function
* Adds `TK_MUTE_MUSIC` (it was interrupting my Spotify, grump grump)
* Adds `tk3 -e 1 -l 1` + `TK_SKIP_LEVEL_INFO` for immediate debug fun

Probably fixes #122.

### CODE REVIEW

File: SRC/CLASSES.CPP [hunk 1]
```diff
@@ -282,32 +283,31 @@ void Player::chk_keys( int index )
...
-    offs[2] = ( ( rny + 20 - reuna )  / 20 ) *level_x_size + ( ( rnx + 10 - reuna2 )  / 20 );
-    offs[3] = ( ( rny + 20 - reuna )  / 20 ) *level_x_size + ( ( rnx + 10 + reuna2 )  / 20 );
-    offs[4] = ( ( rny + 10 - reuna2 )  / 20 ) *level_x_size + ( ( rnx + reuna )  / 20 );
-    offs[5] = ( ( rny + 10 + reuna2 )  / 20 ) *level_x_size + ( ( rnx + reuna )  / 20 );
-    offs[6] = ( ( rny + 10 - reuna2 )  / 20 ) *level_x_size + ( ( rnx + 20 - reuna )  / 20 );
-    offs[7] = ( ( rny + 10 + reuna2 )  / 20 ) *level_x_size + ( ( rnx + 20 - reuna )  / 20 );
-    if ( newy < y && level[offs[0]].type == FLOOR && level[offs[1]].type == FLOOR )
+    int reuna = 4; //  * * chk pointit on näin
+    int reuna2 = 4; // * *
+    if ( num < 12 && rand() % 3 != 0 )
```
Comment (veikkos) [inline SRC/CLASSES.CPP]: Would have added parenthesis.

File: SRC/CLASSES.CPP [hunk 2]
```diff
@@ -282,32 +283,31 @@ void Player::chk_keys( int index )
...
+    {
+        new_effect( 0, BLOOD2, int( x ) + 10, int( y ) + 10, 0, 0 );
+    }
+    float newx = x + ( ( int ) speed*sini[angle] );
+    float newy = y + ( ( int ) speed*cosi[angle] );
+    int rnx = newx;
+    int rny = newy;
+    int type0 = get_block_type_at_coord( rnx + 10 - reuna2, rny + reuna );
```
Comment (veikkos) [inline SRC/CLASSES.CPP]: `int types[]`?

Comment (akx) [reply SRC/CLASSES.CPP]: Useless use of array in my opinion. We never iterate over these, and they're definitely not homogenous values, but each index of the array has a special meaning.
